name: Flutter Composite Action

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Set flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
